### ISSUE TITLE
Master branch protection

### ISSUE THREAD

**Issue by szk2s** [szk2s/spectrum2mpe#23]
Hi @zigen , I am trying to make a branch protection on master branch.  
I'd like to restrict anyone from pushing directly into master.  
So I've made a rule like [this](https://github.com/szk2s/spectrum2mpe/settings/branches).  
Currently it is working when I made push with -f option, but seems not to prevent ordinary push.  
How can I solve this?

**Comment by zigen** [comment]
@szk2s can you add me to collabolator? I cannot see your link because I have no permission to this repo.

**Comment by szk2s** [comment]
Sorry @zigen , I didn't notice. 
You are already a collaborator.
Maybe this rule setting is only available to the owner.
This issue is not so urgent. I will talk it next time I see you .
