### ISSUE TITLE
Use object destructuring to emulate named arguments?

### ISSUE THREAD

**Issue by yuichkun** [szk2s/spectrum2mpe#33]
I see not so few of the functions in this repository takes more than 2 arguments.
Instead of forcing ourselves to always remember the order of arguments, how about we always use objects to pass in arguments.
With the help of ES6 syntax we can do it pretty simply.

ES5 
```javascript
function myFunc(opts) {
  var name = opts.name;
  var age = opts.age;
}

myFunc({ name: 'John', age: 25 });
```

ES6
```javascript
function myFunc({name, age}) {

}
```

reference: https://simonsmith.io/destructuring-objects-as-function-parameters-in-es6/

This may be a personal favor of coding style,  but I believe this prevents a lot of unexpected *undefined* in runtime.

**Comment by satoshi-szk** [comment]
That's great idea!
