### ISSUE TITLE
Let's TypeScript!

### ISSUE THREAD

**Issue by yuichkun** [szk2s/spectrum2mpe#38]
Shall we?

**Comment by azamiya** [comment]
how about this?

https://flow.org/

**Comment by zigen** [comment]
https://fable.io/

**Comment by satoshi-szk** [comment]
Wow, I can't decide...

**Comment by zigen** [comment]
you're the owner of this repository, so you should decide it.
what do you want to decide this? pros and cons? philosophy of the tools?

**Comment by satoshi-szk** [comment]
I have never used any of them.
I will google the pros and cons...

**Comment by satoshi-szk** [comment]
But, First of all, @yuichkun,  What point do you think is the problem in the current code?
And what made you propose typescript...?

**Comment by yuichkun** [comment]
I only wanted type annotation per se, so I don't insist on using any framework in particular.

Actually flow might be easier in this situation because it does not need to be transpiled, i.e. we can leave everything as-is and opt-in type annotations.

**Comment by yuichkun** [comment]
The reason why I would want types is because take the following code:

https://github.com/szk2s/spectrum2mpe/blob/develop/lib/convert.js#L28

Without go seeing the implementation of `txtImport`, I have no way to find out what kind of data it's returning, so it makes reviewing much easier. 
Needless to say that it enhances the development as well.

**Comment by satoshi-szk** [comment]
I took a casual glance at all three documentations, and Flow looks easier than the other two as yuichi said.
I will checkout branch and install Flow.
Thank you for all advices.
