### ISSUE TITLE
長いファイルが変換できない。

### ISSUE THREAD

**Issue by szk2s** [szk2s/spectrum2mpe#7]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

textファイルをinputすると、対応するmpeを吐き出す

## Current Behavior

長いテキストファイルをインプットすると、以下のエラーメッセージ
```
Importing files...


  0 passing (1ms)

Generating melody lines from partials...
(node:42723) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Maximum call stack size exceeded
(node:42723) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Possible Solution

全くわからない。

## Steps to Reproduce

1.  ./test/test.jsの7-8行目のコメントアウトを下のように変える
```
// s2m.convertFromSpear('large_bowl');
s2m.convertFromSpear('long_text.txt')
```
2. コマンド`npm test`

**Comment by zigen** [comment]
`Maximum call stack size exceeded` ということなので関数呼び出しが多すぎるんだな。。。
